CREATE TABLE "clients" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"phone" text,
	"meeting_date" timestamp with time zone NOT NULL,
	"assigned_seller" text NOT NULL,
	"closed" boolean NOT NULL,
	"transcript" text NOT NULL,
	"industry" text,
	"company_size" text,
	"main_pain_point" text,
	"key_objection" text,
	"buying_signal" text,
	"sentiment" text,
	"needs_summary" text,
	"next_steps" text,
	"reasoning" text,
	"prompt_version" text,
	"model_version" text,
	"truncated" boolean DEFAULT false NOT NULL,
	"classification_status" text DEFAULT 'pending' NOT NULL,
	"error_message" text,
	"warnings" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "clients_email_unique" UNIQUE("email")
);
